batch_size: 8
gradient_accumulation_steps: 4
max_steps: 40000
learning_rate: 3e-4
weight_decay: 0.1
warmup_steps: 400
precision: bf16 # options: fp32, fp16, bf16
grad_clip: 1.0
save_interval: 4000
eval_interval: 2000
log_interval: 40
resume_from_checkpoint: null
device: cuda
compile: true
